language: python
python:
    - 2.7
install:
    - virtualenv .
    - pip install -UIr requirements.txt
    - python bootstrap.py
    - bin/buildout
script:
    - bin/test -v1
notifications:
    email: false
