language: python
python:
    - 2.7
install:
    - virtualenv .
    - source ./bin/activate
    - bin/pip install -UIr requirements.txt
    - bin/python bootstrap.py
    - bin/buildout
script:
    - bin/test -v1
notifications:
    email: false
